import {
  FLYER1,
  FLYER10,
  FLYER11,
  FLYER12,
  FLYER13,
  FLYER15,
  FLYER16,
  FLYER17,
  FLYER18,
  FLYER19,
  FLYER2,
  FLYER20,
  FLYER3,
  FLYER4,
  FLYER5,
  FLYER6,
  FLYER7,
  FLYER8,
  FLYER9,
  WEBSITE1,
  WEBSITE2,
  WEBSITE3,
  WEBSITE4,
  WEBSITE5,
  WEBSITE6,
} from "../ASSETS/IMAGES/images";

export const navLinks = [
  {
    id: "1",
    name: "Home",
    path: "/",
  },
  {
    id: "2",
    name: "Services",
    path: "/services",
  },
  {
    id: "3",
    name: "Projects",
    path: "/projects",
  },
  {
    id: "4",
    name: "About",
    path: "/about",
  },
];

export const myPortfolio = [
  {
    id: "1",
    name: "Mandyz Elite Restaurant",
    image: WEBSITE1,
    link: null,
    type: "WEBSITE",
  },
  {
    id: "2",
    name: "Vogue Wears",
    image: WEBSITE2,
    link: "www.voguewears.vercel.app",
    type: "WEBSITE",
  },
  {
    id: "3",
    name: "Hair Haven",
    image: WEBSITE3,
    link: null,
    type: "WEBSITE",
  },
  {
    id: "4",
    name: "Freightiex",
    image: WEBSITE4,
    link: null,
    type: "WEBSITE",
  },
  {
    id: "5",
    name: "Restaurant Website",
    image: WEBSITE5,
    link: null,
    type: "WEBSITE",
  },
  {
    id: "5",
    name: "Deluxe Token Mint",
    image: WEBSITE6,
    link: null,
    type: "WEBSITE",
  },
  {
    id: "6",
    name: "Mandyz Sip & Bite",
    image: FLYER1,
    link: null,
    type: "FLYER",
  },
  {
    id: "7",
    name: "Ice Bath Skit Contest",
    image: FLYER2,
    link: null,
    type: "FLYER",
  },
  {
    id: "8",
    name: "Ice Bath Reservation",
    image: FLYER3,
    link: null,
    type: "FLYER",
  },
  {
    id: "9",
    name: "New Month Flyer",
    image: FLYER4,
    link: null,
    type: "FLYER",
  },
  {
    id: "10",
    name: "Promotional Flyer",
    image: FLYER5,
    link: null,
    type: "FLYER",
  },
  {
    id: "11",
    name: "Web Design Service",
    image: FLYER6,
    link: null,
    type: "FLYER",
  },
  {
    id: "12",
    name: "Event Planning Service",
    image: FLYER7,
    link: null,
    type: "FLYER",
  },
  {
    id: "13",
    name: "Business Registration",
    image: FLYER8,
    link: null,
    type: "FLYER",
  },
  {
    id: "14",
    name: "Eid Mubarak",
    image: FLYER9,
    link: null,
    type: "FLYER",
  },
  {
    id: "15",
    name: "Business Registration",
    image: FLYER10,
    link: null,
    type: "FLYER",
  },
  {
    id: "16",
    name: "Business Registration",
    image: FLYER11,
    link: null,
    type: "FLYER",
  },
  {
    id: "17",
    name: "Web Design Service",
    image: FLYER12,
    link: null,
    type: "FLYER",
  },
  {
    id: "18",
    name: "Sponsorhip Benefits",
    image: FLYER13,
    link: null,
    type: "FLYER",
  },
  {
    id: "19",
    name: "Clothing Store",
    image: FLYER15,
    link: null,
    type: "FLYER",
  },
  {
    id: "20",
    name: "Ice Bath Event",
    image: FLYER16,
    link: null,
    type: "FLYER",
  },
  {
    id: "21",
    name: "Event Planning Service",
    image: FLYER17,
    link: null,
    type: "FLYER",
  },
  {
    id: "22",
    name: "Game Night",
    image: FLYER18,
    link: null,
    type: "FLYER",
  },
  {
    id: "23",
    name: "Ladies Night",
    image: FLYER19,
    link: null,
    type: "FLYER",
  },
  {
    id: "24",
    name: "Cleaning Company",
    image: FLYER20,
    link: null,
    type: "FLYER",
  },
];

// export const portfolio = [
//   {
//     id: "1",
//     name: "Mandyz Elite Restaurant",
//     image: FLYER4,
//     link: null,
//     type: "WEBSITE",
//   },
//   {
//     id: "2",
//     name: "Vogue Wears",
//     image: FLYER5,
//     link: "www.voguewears.vercel.app",
//     type: "WEBSITE",
//   },
//   {
//     id: "3",
//     name: "Hair Haven",
//     image: FLYER6,
//     link: null,
//     type: "WEBSITE",
//   },
//   {
//     id: "4",
//     name: "Freightiex",
//     image: FLYER10,
//     link: null,
//     type: "WEBSITE",
//   },
//   {
//     id: "5",
//     name: "Restaurant Website",
//     image: FLYER8,
//     link: null,
//     type: "WEBSITE",
//   },
//   {
//     id: "6",
//     name: "Mandyz Sip & Bite",
//     image: FLYER1,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "7",
//     name: "Ice Bath Skit Contest",
//     image: FLYER2,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "8",
//     name: "Ice Bath Reservation",
//     image: FLYER3,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "9",
//     name: "New Month Flyer",
//     image: FLYER11,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "10",
//     name: "New Month Flyer",
//     image: FLYER27,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "11",
//     name: "New Month Flyer",
//     image: FLYER28,
//     link: null,
//     type: "FLYER",
//   },

//   {
//     id: "12",
//     name: "New Month Flyer",
//     image: FLYER12,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "13",
//     name: "New Month Flyer",
//     image: FLYER13,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "14",
//     name: "New Month Flyer",
//     image: FLYER14,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "15",
//     name: "New Month Flyer",
//     image: FLYER15,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "16",
//     name: "New Month Flyer",
//     image: FLYER16,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "17",
//     name: "New Month Flyer",
//     image: FLYER17,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "18",
//     name: "New Month Flyer",
//     image: FLYER18,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "19",
//     name: "New Month Flyer",
//     image: FLYER19,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "20",
//     name: "New Month Flyer",
//     image: FLYER20,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "21",
//     name: "New Month Flyer",
//     image: FLYER21,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "22",
//     name: "New Month Flyer",
//     image: FLYER22,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "23",
//     name: "New Month Flyer",
//     image: FLYER23,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "24",
//     name: "New Month Flyer",
//     image: FLYER24,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "25",
//     name: "New Month Flyer",
//     image: FLYER25,
//     link: null,
//     type: "FLYER",
//   },
//   {
//     id: "26",
//     name: "New Month Flyer",
//     image: FLYER26,
//     link: null,
//     type: "FLYER",
//   },
// ];
